### ISSUE TITLE
setVisualState vs. callProjectApi 

### ISSUE THREAD

**Issue by RohanSM123** [alan-ai/alan-sdk-web#22]
What is the difference between setVisualState and callProjectApi methods?

**Comment by annmirosh** [comment]
Hi, @RohanSM123 ,

both methods can be used for sending data to the voice script.

You can use `visualState` to pass the current state of the app to the voice script. `visualState` can be helpful if you need to know the app state to adjust the logic in the dialog flow, for example, filter out some voice commands, give responses applicable to this state and so on.

The `projectAPI` method has a more general usage. It can help if you need to pass any data to the voice script or perform some actions (call functions, set variable values) without a voice command.
