### ISSUE TITLE
Alan Button Not Visible

### ISSUE THREAD

**Issue by avajshah** [alan-ai/alan-sdk-web#30]
## Bug Report:

Please include a simple reproducing example.

### What is the current behavior?

I added the Alan Button in my code but I cannot see it on the page.

### What is the expected behavior?

The button isn't showing up on the page after following the video.

Browser - Chrome

* What's your use case? (Tell us about your application and what problem you're trying to solve.)
Just trying to play around and get familiar with this platform. 

Hope this can be solved soon!

**Comment by okolyachko** [comment]
Hi avajshah, 

Please make sure you add all the components required for the Alan button to your webpage. The easiest way to check it is to see instructions provided in the Alan Studio itself: go to the Integrations section, in the Embed Code Example section, click the tab for the necessary platform and have a look at the integration steps there:

![embed-code](https://user-images.githubusercontent.com/64134529/90418962-82239700-e0be-11ea-9e9d-5bec5f35e58d.png)

For example, for a regular webpage, you need to:

1. Add Lato Google Font to the head section.
2. Add a node that will be a container for the Alan button.
3. Add the Alan button in the script tag.

If this is not the case, please let us know.
