### ISSUE TITLE
Defining context() in studio editor fails instantaneously.

### ISSUE THREAD

**Issue by divakarrana** [alan-ai/alan-sdk-web#43]
### Steps to reproduce:
Go to alan studio editor and type `let confirm = context();` //Editor crashes
However, this works when we copy paste a code with an already defined callback function inside a context();

Also, I've to clear out my cache to remove the so-called bad code from localStorage to make it work again.

### What is the current behavior?
Editor fails instantaneously with no particular error info.

### What is the expected behavior?
The editor should allow writing callback function after defining context but it fails as soon as we define the empty `context();`

### Which versions of alan-sdk-web are you using, and which browsers / OS's are affected by this issue? 
I don't think it has something to do with the framework but I am using React17.0.1
Browser: Google Chrome version 87.0.4280.66 (Official Build) (64-bit)

Browser - Google Chrome version 87.0.4280.66 (Official Build) (64-bit)
OS - Windows10
Framework - React17
alan-sdk-web - 1.8.5

Here's a screenshot of what I am redirected to after the issue is encountered.

![2F7EDC960C5B44A7988BC306679C05AB](https://user-images.githubusercontent.com/38125863/99938194-4bc87880-2d8d-11eb-98e7-445ab134890f.png)

**Comment by divakarrana** [comment]
Looks like this is not specific to only `context`. Facing the same issue with `p.then()` as well.

**Comment by annmirosh** [comment]
@divakarrana, thanks for your interest in the Alan Studio, and sorry for the delay with the response - at the current moment this issue has already been fixed.
